name: dev-pypro
channels:
  - defaults
dependencies:
  - pytest-cov
  - python-dotenv
  - requests
  - types-pyyaml
  - pytest
  - just
  - python=3.11
  - pyyaml
  - mypy=1.17.1
  - pandas
  - pip-audit
  - pre-commit
  - ruff=0.15.1
  - types-requests
  - pandas-stubs
  - bandit
  - hypothesis
  - conda-lock
