# environment.yml (prod) — runtime only
name: pypro
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - python-dotenv
  - requests
  - pyyaml
  - ipykernel
  - ipywidgets
  - matplotlib
